//
// DimensionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class DimensionsAPI {

    /**
     Competitor details
     
     - parameter projectId: (query) Project ID 
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CompetitorDetails
     */
    open class func getCompetitorDetails(projectId: Int, id: Int, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) -> CompetitorDetails {
        return try await getCompetitorDetailsWithRequestBuilder(projectId: projectId, id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Competitor details
     - GET /dimensions/competitors/{id}
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CompetitorDetails> 
     */
    open class func getCompetitorDetailsWithRequestBuilder(projectId: Int, id: Int, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<CompetitorDetails> {
        var localVariablePath = "/dimensions/competitors/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CompetitorDetails>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Project details
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProjectDetails
     */
    open class func getProjectDetails(id: Int, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) -> ProjectDetails {
        return try await getProjectDetailsWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Project details
     - GET /dimensions/projects/{id}
     - Detailed info for one project: matching_names, industry, business model, primary products, target audience, brand voice, locale, app store IDs, stats (incl. prompts_by_brand_kind counts) and data_coverage (models, countries and languages with data).
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProjectDetails> 
     */
    open class func getProjectDetailsWithRequestBuilder(id: Int, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<ProjectDetails> {
        var localVariablePath = "/dimensions/projects/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProjectDetails>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter output
     */
    public enum Output_listAgentBots: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     AI bot catalog (Scale+)
     
     - parameter projectId: (query) Project ID 
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AgentBotsResponse
     */
    open class func listAgentBots(projectId: Int, output: Output_listAgentBots? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) -> AgentBotsResponse {
        return try await listAgentBotsWithRequestBuilder(projectId: projectId, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     AI bot catalog (Scale+)
     - GET /dimensions/agent_bots
     - Static catalog of AI bots that Agent Analytics can identify. Useful for rendering filter UIs that mirror our internal classification (slug, display name, company, category, Cloudflare verified-bot mapping, description). Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED. The equivalent MCP tool list_agent_bots is available on all plans.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AgentBotsResponse> 
     */
    open class func listAgentBotsWithRequestBuilder(projectId: Int, output: Output_listAgentBots? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<AgentBotsResponse> {
        let localVariablePath = "/dimensions/agent_bots"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AgentBotsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter model
     */
    public enum Model_listAllCitations: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listAllCitations: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List all citations (brand + competitor)
     
     - parameter projectId: (query) Project ID 
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listAllCitations(projectId: Int, competitors: String? = nil, page: Int? = nil, perPage: Int? = nil, model: Model_listAllCitations? = nil, collectionId: Int? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listAllCitations? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listAllCitationsWithRequestBuilder(projectId: projectId, competitors: competitors, page: page, perPage: perPage, model: model, collectionId: collectionId, prompt: prompt, from: from, to: to, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all citations (brand + competitor)
     - GET /dimensions/all_citations
     - Unified citations stream with an `actor_type` field on each record. Includes visible citations and background source references; background references use position 0, meaning no visible rank.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listAllCitationsWithRequestBuilder(projectId: Int, competitors: String? = nil, page: Int? = nil, perPage: Int? = nil, model: Model_listAllCitations? = nil, collectionId: Int? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listAllCitations? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/all_citations"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "competitors": (wrappedValue: competitors?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter model
     */
    public enum Model_listAllMentions: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listAllMentions: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List all mentions (brand + competitor)
     
     - parameter projectId: (query) Project ID 
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listAllMentions(projectId: Int, competitors: String? = nil, page: Int? = nil, perPage: Int? = nil, model: Model_listAllMentions? = nil, collectionId: Int? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listAllMentions? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listAllMentionsWithRequestBuilder(projectId: projectId, competitors: competitors, page: page, perPage: perPage, model: model, collectionId: collectionId, prompt: prompt, from: from, to: to, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all mentions (brand + competitor)
     - GET /dimensions/all_mentions
     - Unified mentions stream. Each record has an `actor_type` field (`project` or `competitor`) so the same payload covers both.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listAllMentionsWithRequestBuilder(projectId: Int, competitors: String? = nil, page: Int? = nil, perPage: Int? = nil, model: Model_listAllMentions? = nil, collectionId: Int? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listAllMentions? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/all_mentions"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "competitors": (wrappedValue: competitors?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter model
     */
    public enum Model_listCitations: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listCitations: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List brand citations
     
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listCitations(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listCitations? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listCitations? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listCitationsWithRequestBuilder(projectId: projectId, page: page, perPage: perPage, model: model, collectionId: collectionId, countryCode: countryCode, languageCode: languageCode, prompt: prompt, from: from, to: to, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List brand citations
     - GET /dimensions/citations
     - Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listCitationsWithRequestBuilder(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listCitations? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listCitations? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/citations"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "country_code": (wrappedValue: countryCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "language_code": (wrappedValue: languageCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter output
     */
    public enum Output_listCollections: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List tags/collections
     
     - parameter projectId: (query) Project ID 
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listCollections(projectId: Int, output: Output_listCollections? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listCollectionsWithRequestBuilder(projectId: projectId, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List tags/collections
     - GET /dimensions/collections
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listCollectionsWithRequestBuilder(projectId: Int, output: Output_listCollections? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/collections"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter model
     */
    public enum Model_listCompetitorCitations: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listCompetitorCitations: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List competitor citations
     
     - parameter projectId: (query) Project ID 
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listCompetitorCitations(projectId: Int, competitors: String? = nil, page: Int? = nil, perPage: Int? = nil, model: Model_listCompetitorCitations? = nil, collectionId: Int? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listCompetitorCitations? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listCompetitorCitationsWithRequestBuilder(projectId: projectId, competitors: competitors, page: page, perPage: perPage, model: model, collectionId: collectionId, prompt: prompt, from: from, to: to, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List competitor citations
     - GET /dimensions/competitor_citations
     - Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listCompetitorCitationsWithRequestBuilder(projectId: Int, competitors: String? = nil, page: Int? = nil, perPage: Int? = nil, model: Model_listCompetitorCitations? = nil, collectionId: Int? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listCompetitorCitations? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/competitor_citations"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "competitors": (wrappedValue: competitors?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter model
     */
    public enum Model_listCompetitorMentions: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listCompetitorMentions: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List competitor mentions
     
     - parameter projectId: (query) Project ID 
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listCompetitorMentions(projectId: Int, competitors: String? = nil, page: Int? = nil, perPage: Int? = nil, model: Model_listCompetitorMentions? = nil, collectionId: Int? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listCompetitorMentions? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listCompetitorMentionsWithRequestBuilder(projectId: projectId, competitors: competitors, page: page, perPage: perPage, model: model, collectionId: collectionId, prompt: prompt, from: from, to: to, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List competitor mentions
     - GET /dimensions/competitor_mentions
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listCompetitorMentionsWithRequestBuilder(projectId: Int, competitors: String? = nil, page: Int? = nil, perPage: Int? = nil, model: Model_listCompetitorMentions? = nil, collectionId: Int? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listCompetitorMentions? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/competitor_mentions"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "competitors": (wrappedValue: competitors?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter output
     */
    public enum Output_listCompetitors: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List competitors
     
     - parameter projectId: (query) Project ID 
     - parameter includeProjectBrand: (query) When true, prepends the project brand with actor_type&#x3D;project and is_own&#x3D;true (optional, default to false)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListCompetitors200Response
     */
    open class func listCompetitors(projectId: Int, includeProjectBrand: Bool? = nil, output: Output_listCompetitors? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) -> ListCompetitors200Response {
        return try await listCompetitorsWithRequestBuilder(projectId: projectId, includeProjectBrand: includeProjectBrand, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List competitors
     - GET /dimensions/competitors
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter includeProjectBrand: (query) When true, prepends the project brand with actor_type&#x3D;project and is_own&#x3D;true (optional, default to false)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListCompetitors200Response> 
     */
    open class func listCompetitorsWithRequestBuilder(projectId: Int, includeProjectBrand: Bool? = nil, output: Output_listCompetitors? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<ListCompetitors200Response> {
        let localVariablePath = "/dimensions/competitors"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "include_project_brand": (wrappedValue: includeProjectBrand?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListCompetitors200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List locales with data
     
     - parameter projectId: (query) Project ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listLocales(projectId: Int, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listLocalesWithRequestBuilder(projectId: projectId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List locales with data
     - GET /dimensions/locales
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listLocalesWithRequestBuilder(projectId: Int, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/locales"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter model
     */
    public enum Model_listMentions: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listMentions: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List brand mentions
     
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listMentions(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listMentions? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listMentions? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listMentionsWithRequestBuilder(projectId: projectId, page: page, perPage: perPage, model: model, collectionId: collectionId, countryCode: countryCode, languageCode: languageCode, prompt: prompt, from: from, to: to, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List brand mentions
     - GET /dimensions/mentions
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listMentionsWithRequestBuilder(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listMentions? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listMentions? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/mentions"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "country_code": (wrappedValue: countryCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "language_code": (wrappedValue: languageCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List models with data
     
     - parameter projectId: (query) Project ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listModels(projectId: Int, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listModelsWithRequestBuilder(projectId: projectId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List models with data
     - GET /dimensions/models
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listModelsWithRequestBuilder(projectId: Int, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/models"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter output
     */
    public enum Output_listProjects: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List projects
     
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListProjects200Response
     */
    open class func listProjects(output: Output_listProjects? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) -> ListProjects200Response {
        return try await listProjectsWithRequestBuilder(output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List projects
     - GET /dimensions/projects
     - All projects accessible with your API key.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListProjects200Response> 
     */
    open class func listProjectsWithRequestBuilder(output: Output_listProjects? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<ListProjects200Response> {
        let localVariablePath = "/dimensions/projects"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListProjects200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter model
     */
    public enum Model_listPromptExecutions: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
    }

    /**
     * enum for parameter mentionFilter
     */
    public enum MentionFilter_listPromptExecutions: String, Sendable, CaseIterable {
        case mentionsYou = "mentions_you"
        case notMentionsYou = "not_mentions_you"
        case mentionsCompetitor = "mentions_competitor"
        case notMentionsCompetitor = "not_mentions_competitor"
        case youAndCompetitor = "you_and_competitor"
        case competitorNotYou = "competitor_not_you"
        case youNotCompetitor = "you_not_competitor"
        case noBrands = "no_brands"
    }

    /**
     * enum for parameter citationFilter
     */
    public enum CitationFilter_listPromptExecutions: String, Sendable, CaseIterable {
        case citesYou = "cites_you"
        case notCitesYou = "not_cites_you"
        case citesCompetitor = "cites_competitor"
        case notCitesCompetitor = "not_cites_competitor"
        case youAndCompetitor = "you_and_competitor"
        case competitorNotYou = "competitor_not_you"
        case youNotCompetitor = "you_not_competitor"
        case citesNoBrands = "cites_no_brands"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listPromptExecutions: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List prompt executions
     
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter mentionFilter: (query) Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with &#39;competitors&#39; to narrow the competitor side to specific rivals; on a negative cell that reads &#39;none of these&#39;. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value &#39;competitors_only&#39; is still accepted as an alias of competitor_not_you. (optional)
     - parameter citationFilter: (query) Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you). (optional)
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listPromptExecutions(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listPromptExecutions? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, mentionFilter: MentionFilter_listPromptExecutions? = nil, citationFilter: CitationFilter_listPromptExecutions? = nil, competitors: String? = nil, output: Output_listPromptExecutions? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listPromptExecutionsWithRequestBuilder(projectId: projectId, page: page, perPage: perPage, model: model, collectionId: collectionId, countryCode: countryCode, languageCode: languageCode, prompt: prompt, from: from, to: to, mentionFilter: mentionFilter, citationFilter: citationFilter, competitors: competitors, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List prompt executions
     - GET /dimensions/prompt_executions
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter mentionFilter: (query) Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with &#39;competitors&#39; to narrow the competitor side to specific rivals; on a negative cell that reads &#39;none of these&#39;. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value &#39;competitors_only&#39; is still accepted as an alias of competitor_not_you. (optional)
     - parameter citationFilter: (query) Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you). (optional)
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listPromptExecutionsWithRequestBuilder(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listPromptExecutions? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, mentionFilter: MentionFilter_listPromptExecutions? = nil, citationFilter: CitationFilter_listPromptExecutions? = nil, competitors: String? = nil, output: Output_listPromptExecutions? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/prompt_executions"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "country_code": (wrappedValue: countryCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "language_code": (wrappedValue: languageCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "mention_filter": (wrappedValue: mentionFilter?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "citation_filter": (wrappedValue: citationFilter?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "competitors": (wrappedValue: competitors?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter model
     */
    public enum Model_listPrompts: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
    }

    /**
     * enum for parameter promptType
     */
    public enum PromptType_listPrompts: String, Sendable, CaseIterable {
        case informational = "informational"
        case navigational = "navigational"
        case commercial = "commercial"
        case transactional = "transactional"
    }

    /**
     * enum for parameter brandKind
     */
    public enum BrandKind_listPrompts: String, Sendable, CaseIterable {
        case brand = "brand"
        case brandOther = "brand_other"
        case nonBrand = "non_brand"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listPrompts: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List prompts
     
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter promptType: (query) Filter by prompt type (search intent) (optional)
     - parameter brandKind: (query) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listPrompts(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listPrompts? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, promptType: PromptType_listPrompts? = nil, brandKind: BrandKind_listPrompts? = nil, from: Date? = nil, to: Date? = nil, output: Output_listPrompts? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listPromptsWithRequestBuilder(projectId: projectId, page: page, perPage: perPage, model: model, collectionId: collectionId, countryCode: countryCode, languageCode: languageCode, promptType: promptType, brandKind: brandKind, from: from, to: to, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List prompts
     - GET /dimensions/prompts
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter promptType: (query) Filter by prompt type (search intent) (optional)
     - parameter brandKind: (query) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listPromptsWithRequestBuilder(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listPrompts? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, promptType: PromptType_listPrompts? = nil, brandKind: BrandKind_listPrompts? = nil, from: Date? = nil, to: Date? = nil, output: Output_listPrompts? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/prompts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "country_code": (wrappedValue: countryCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "language_code": (wrappedValue: languageCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt_type": (wrappedValue: promptType?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "brand_kind": (wrappedValue: brandKind?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter output
     */
    public enum Output_listSentimentCategories: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List sentiment categories
     
     - parameter projectId: (query) Project ID 
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listSentimentCategories(projectId: Int, output: Output_listSentimentCategories? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listSentimentCategoriesWithRequestBuilder(projectId: projectId, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List sentiment categories
     - GET /dimensions/sentiments
     - Sentiment metric keys + labels + colors. For records, use /sentiments.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listSentimentCategoriesWithRequestBuilder(projectId: Int, output: Output_listSentimentCategories? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/sentiments"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter model
     */
    public enum Model_listSources: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
    }

    /**
     * enum for parameter sourceType
     */
    public enum SourceType_listSources: String, Sendable, CaseIterable {
        case owned = "owned"
        case competitor = "competitor"
        case thirdParty = "third_party"
    }

    /**
     * enum for parameter mentionFilter
     */
    public enum MentionFilter_listSources: String, Sendable, CaseIterable {
        case mentionsYou = "mentions_you"
        case notMentionsYou = "not_mentions_you"
        case mentionsCompetitor = "mentions_competitor"
        case notMentionsCompetitor = "not_mentions_competitor"
        case youAndCompetitor = "you_and_competitor"
        case competitorNotYou = "competitor_not_you"
        case youNotCompetitor = "you_not_competitor"
        case noBrands = "no_brands"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listSources: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List source URLs
     
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter sourceType: (query) Filter by source ownership. Owned and competitor matching honor the project&#39;s exact-subdomain setting. (optional)
     - parameter mentionFilter: (query) Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with &#39;competitors&#39; to narrow the competitor side to specific rivals; on a negative cell that reads &#39;none of these&#39;. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value &#39;competitors_only&#39; is still accepted as an alias of competitor_not_you. (optional)
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listSources(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listSources? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, sourceType: SourceType_listSources? = nil, mentionFilter: MentionFilter_listSources? = nil, competitors: String? = nil, output: Output_listSources? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listSourcesWithRequestBuilder(projectId: projectId, page: page, perPage: perPage, model: model, collectionId: collectionId, countryCode: countryCode, languageCode: languageCode, prompt: prompt, from: from, to: to, sourceType: sourceType, mentionFilter: mentionFilter, competitors: competitors, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List source URLs
     - GET /dimensions/sources
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query)  (optional)
     - parameter countryCode: (query) ISO country code (e.g. US, GB, DE) (optional)
     - parameter languageCode: (query) ISO language code (e.g. en, es, de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter sourceType: (query) Filter by source ownership. Owned and competitor matching honor the project&#39;s exact-subdomain setting. (optional)
     - parameter mentionFilter: (query) Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with &#39;competitors&#39; to narrow the competitor side to specific rivals; on a negative cell that reads &#39;none of these&#39;. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value &#39;competitors_only&#39; is still accepted as an alias of competitor_not_you. (optional)
     - parameter competitors: (query) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listSourcesWithRequestBuilder(projectId: Int, page: Int? = nil, perPage: Int? = nil, model: Model_listSources? = nil, collectionId: Int? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, from: Date? = nil, to: Date? = nil, sourceType: SourceType_listSources? = nil, mentionFilter: MentionFilter_listSources? = nil, competitors: String? = nil, output: Output_listSources? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/sources"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "country_code": (wrappedValue: countryCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "language_code": (wrappedValue: languageCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "source_type": (wrappedValue: sourceType?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "mention_filter": (wrappedValue: mentionFilter?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "competitors": (wrappedValue: competitors?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter output
     */
    public enum Output_listTags: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List tags (alias for /collections)
     
     - parameter projectId: (query) Project ID 
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listTags(projectId: Int, output: Output_listTags? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listTagsWithRequestBuilder(projectId: projectId, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List tags (alias for /collections)
     - GET /dimensions/tags
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listTagsWithRequestBuilder(projectId: Int, output: Output_listTags? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/tags"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
