//
// HealthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class HealthAPI {

    /**
     Health check
     
     - parameter projectId: (query) Optional project to verify access for (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Ping200Response
     */
    open class func ping(projectId: Int? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) -> Ping200Response {
        return try await pingWithRequestBuilder(projectId: projectId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Health check
     - GET /ping
     - Validates the API key and optionally pings a project. Returns the authenticated user_id, project (if project_id is supplied), and a request_id.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Optional project to verify access for (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Ping200Response> 
     */
    open class func pingWithRequestBuilder(projectId: Int? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Ping200Response> {
        let localVariablePath = "/ping"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        let localVariableQueryItems: [String: (wrappedValue: (any Sendable)?, isExplode: Bool)] = [
            "project_id": (wrappedValue: projectId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ]
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems(localVariableQueryItems)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Ping200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
