//
// ShoppingAdsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ShoppingAdsAPI {

    /**
     * enum for parameter view
     */
    public enum View_listAds: String, Sendable, CaseIterable {
        case advertisers = "advertisers"
        case ads = "ads"
    }

    /**
     * enum for parameter order
     */
    public enum Order_listAds: String, Sendable, CaseIterable {
        case ads = "ads"
        case prompts = "prompts"
        case avgPosition = "avg_position"
        case domain = "domain"
        case recent = "recent"
        case oldest = "oldest"
        case position = "position"
    }

    /**
     * enum for parameter direction
     */
    public enum Direction_listAds: String, Sendable, CaseIterable {
        case asc = "asc"
        case desc = "desc"
    }

    /**
     * enum for parameter model
     */
    public enum Model_listAds: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
        case naverAi = "naver_ai"
        case baiduAi = "baidu_ai"
    }

    /**
     * enum for parameter brandKind
     */
    public enum BrandKind_listAds: String, Sendable, CaseIterable {
        case brand = "brand"
        case brandOther = "brand_other"
        case nonBrand = "non_brand"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listAds: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List AI ad placements
     
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter view: (query) Row shape: one per advertising domain, or one per placement (optional, default to .advertisers)
     - parameter owned: (query) Return only placements identified as the tracked brand&#39;s own (view&#x3D;ads) (optional)
     - parameter order: (query) Sort field; the allowed set depends on view (optional)
     - parameter direction: (query) Sort direction for view&#x3D;advertisers. Defaults to desc, except avg_position and domain which default to asc. (optional)
     - parameter query: (query) Case-insensitive substring filter on the ad title, domain or snippet (optional)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
     - parameter countryCode: (query) One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     - parameter languageCode: (query) One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter promptType: (query) One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     - parameter brandKind: (query) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     - parameter range: (query) Number of days to look back (alternative to from/to) (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listAds(projectId: Int, page: Int? = nil, perPage: Int? = nil, view: View_listAds? = nil, owned: Bool? = nil, order: Order_listAds? = nil, direction: Direction_listAds? = nil, query: String? = nil, model: Model_listAds? = nil, collectionId: String? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, promptType: String? = nil, brandKind: BrandKind_listAds? = nil, range: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listAds? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listAdsWithRequestBuilder(projectId: projectId, page: page, perPage: perPage, view: view, owned: owned, order: order, direction: direction, query: query, model: model, collectionId: collectionId, countryCode: countryCode, languageCode: languageCode, prompt: prompt, promptType: promptType, brandKind: brandKind, range: range, from: from, to: to, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List AI ad placements
     - GET /dimensions/ads
     - Paid placements returned inside AI answers. view=advertisers (default) returns one row per advertising domain with its placement count, prompt reach and average and best position; view=ads returns the individual placements with title, snippet, position and the prompt that triggered them. Position 1 is the best slot, so a LOWER average position is better. Requires the Scale plan or above.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter view: (query) Row shape: one per advertising domain, or one per placement (optional, default to .advertisers)
     - parameter owned: (query) Return only placements identified as the tracked brand&#39;s own (view&#x3D;ads) (optional)
     - parameter order: (query) Sort field; the allowed set depends on view (optional)
     - parameter direction: (query) Sort direction for view&#x3D;advertisers. Defaults to desc, except avg_position and domain which default to asc. (optional)
     - parameter query: (query) Case-insensitive substring filter on the ad title, domain or snippet (optional)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
     - parameter countryCode: (query) One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     - parameter languageCode: (query) One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter promptType: (query) One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     - parameter brandKind: (query) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     - parameter range: (query) Number of days to look back (alternative to from/to) (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listAdsWithRequestBuilder(projectId: Int, page: Int? = nil, perPage: Int? = nil, view: View_listAds? = nil, owned: Bool? = nil, order: Order_listAds? = nil, direction: Direction_listAds? = nil, query: String? = nil, model: Model_listAds? = nil, collectionId: String? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, promptType: String? = nil, brandKind: BrandKind_listAds? = nil, range: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listAds? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/ads"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        let localVariableQueryItems: [String: (wrappedValue: (any Sendable)?, isExplode: Bool)] = [
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "view": (wrappedValue: view?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "owned": (wrappedValue: owned?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "order": (wrappedValue: order?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "direction": (wrappedValue: direction?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "query": (wrappedValue: query?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "country_code": (wrappedValue: countryCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "language_code": (wrappedValue: languageCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt_type": (wrappedValue: promptType?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "brand_kind": (wrappedValue: brandKind?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "range": (wrappedValue: range?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ]
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems(localVariableQueryItems)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter view
     */
    public enum View_listShopping: String, Sendable, CaseIterable {
        case products = "products"
        case merchants = "merchants"
    }

    /**
     * enum for parameter order
     */
    public enum Order_listShopping: String, Sendable, CaseIterable {
        case appearances = "appearances"
        case price = "price"
        case rating = "rating"
        case title = "title"
        case products = "products"
        case avgPrice = "avg_price"
        case avgRating = "avg_rating"
        case merchant = "merchant"
    }

    /**
     * enum for parameter direction
     */
    public enum Direction_listShopping: String, Sendable, CaseIterable {
        case asc = "asc"
        case desc = "desc"
    }

    /**
     * enum for parameter model
     */
    public enum Model_listShopping: String, Sendable, CaseIterable {
        case chatgpt = "chatgpt"
        case perplexity = "perplexity"
        case gemini = "gemini"
        case aiOverview = "ai_overview"
        case aiMode = "ai_mode"
        case copilot = "copilot"
        case claude = "claude"
        case grok = "grok"
        case deepseek = "deepseek"
        case metaAi = "meta_ai"
        case amazonRufus = "amazon_rufus"
        case naverAi = "naver_ai"
        case baiduAi = "baidu_ai"
    }

    /**
     * enum for parameter brandKind
     */
    public enum BrandKind_listShopping: String, Sendable, CaseIterable {
        case brand = "brand"
        case brandOther = "brand_other"
        case nonBrand = "non_brand"
    }

    /**
     * enum for parameter output
     */
    public enum Output_listShopping: String, Sendable, CaseIterable {
        case flat = "flat"
        case csv = "csv"
    }

    /**
     List shopping results
     
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter view: (query) Row shape: one per distinct product, or one per merchant (optional, default to .products)
     - parameter owned: (query) Return only products identified as the tracked brand&#39;s own. On view&#x3D;merchants this narrows to the merchants selling those products; the totals block stays account-wide. (optional)
     - parameter order: (query) Sort field; the allowed set depends on view (optional)
     - parameter direction: (query)  (optional, default to .desc)
     - parameter query: (query) Case-insensitive substring filter on the product title (optional)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
     - parameter countryCode: (query) One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     - parameter languageCode: (query) One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter promptType: (query) One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     - parameter brandKind: (query) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     - parameter range: (query) Number of days to look back (alternative to from/to) (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func listShopping(projectId: Int, page: Int? = nil, perPage: Int? = nil, view: View_listShopping? = nil, owned: Bool? = nil, order: Order_listShopping? = nil, direction: Direction_listShopping? = nil, query: String? = nil, model: Model_listShopping? = nil, collectionId: String? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, promptType: String? = nil, brandKind: BrandKind_listShopping? = nil, range: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listShopping? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await listShoppingWithRequestBuilder(projectId: projectId, page: page, perPage: perPage, view: view, owned: owned, order: order, direction: direction, query: query, model: model, collectionId: collectionId, countryCode: countryCode, languageCode: languageCode, prompt: prompt, promptType: promptType, brandKind: brandKind, range: range, from: from, to: to, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List shopping results
     - GET /dimensions/shopping
     - Product cards returned inside AI answers. view=products (default) returns one row per distinct product, merged across executions, with its appearance count, price range, rating and whether it is yours, plus a currency_count saying how many currencies it was priced in (above 1 means the row reports its highest-priced listing and min_price may be another currency); view=merchants returns one row per selling merchant, with a currency field naming the money its price range and average are expressed in (providers price each market in its own currency, so a merchant that sells in more than one reports the currency most of its prices use). Every response also carries a totals block matching the KPI cards in the app, whose avg_price is computed inside the single currency named by avg_price_currency. Requires the Scale plan or above.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter projectId: (query) Project ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter view: (query) Row shape: one per distinct product, or one per merchant (optional, default to .products)
     - parameter owned: (query) Return only products identified as the tracked brand&#39;s own. On view&#x3D;merchants this narrows to the merchants selling those products; the totals block stays account-wide. (optional)
     - parameter order: (query) Sort field; the allowed set depends on view (optional)
     - parameter direction: (query)  (optional, default to .desc)
     - parameter query: (query) Case-insensitive substring filter on the product title (optional)
     - parameter model: (query) Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     - parameter collectionId: (query) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
     - parameter countryCode: (query) One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     - parameter languageCode: (query) One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     - parameter prompt: (query) Filter by prompt ID (optional)
     - parameter promptType: (query) One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     - parameter brandKind: (query) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     - parameter range: (query) Number of days to look back (alternative to from/to) (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     - parameter output: (query) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func listShoppingWithRequestBuilder(projectId: Int, page: Int? = nil, perPage: Int? = nil, view: View_listShopping? = nil, owned: Bool? = nil, order: Order_listShopping? = nil, direction: Direction_listShopping? = nil, query: String? = nil, model: Model_listShopping? = nil, collectionId: String? = nil, countryCode: String? = nil, languageCode: String? = nil, prompt: Int? = nil, promptType: String? = nil, brandKind: BrandKind_listShopping? = nil, range: Int? = nil, from: Date? = nil, to: Date? = nil, output: Output_listShopping? = nil, apiConfiguration: LLMPulseAPIConfiguration = LLMPulseAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/dimensions/shopping"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        let localVariableQueryItems: [String: (wrappedValue: (any Sendable)?, isExplode: Bool)] = [
            "project_id": (wrappedValue: projectId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "view": (wrappedValue: view?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "owned": (wrappedValue: owned?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "order": (wrappedValue: order?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "direction": (wrappedValue: direction?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "query": (wrappedValue: query?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "model": (wrappedValue: model?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "country_code": (wrappedValue: countryCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "language_code": (wrappedValue: languageCode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt": (wrappedValue: prompt?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "prompt_type": (wrappedValue: promptType?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "brand_kind": (wrappedValue: brandKind?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "range": (wrappedValue: range?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "output": (wrappedValue: output?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ]
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems(localVariableQueryItems)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
