//
// AccountCapacity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A ceiling with no usage counter attached. limit is null when unlimited is true. */
public struct AccountCapacity: Sendable, Codable, Hashable {

    public var limit: Int?
    public var unlimited: Bool?

    public init(limit: Int? = nil, unlimited: Bool? = nil) {
        self.limit = limit
        self.unlimited = unlimited
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limit
        case unlimited
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(unlimited, forKey: .unlimited)
    }
}

