//
// AccountQuota.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A consumable quota. limit and remaining are null when unlimited is true. */
public struct AccountQuota: Sendable, Codable, Hashable {

    public var limit: Int?
    public var used: Int?
    public var remaining: Int?
    public var unlimited: Bool?
    /** Reset window for quotas that reset (e.g. month) */
    public var period: String?

    public init(limit: Int? = nil, used: Int? = nil, remaining: Int? = nil, unlimited: Bool? = nil, period: String? = nil) {
        self.limit = limit
        self.used = used
        self.remaining = remaining
        self.unlimited = unlimited
        self.period = period
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limit
        case used
        case remaining
        case unlimited
        case period
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(used, forKey: .used)
        try container.encodeIfPresent(remaining, forKey: .remaining)
        try container.encodeIfPresent(unlimited, forKey: .unlimited)
        try container.encodeIfPresent(period, forKey: .period)
    }
}

