//
// Actor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Actor: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case project = "project"
        case competitor = "competitor"
    }
    public var type: ModelType?
    public var id: Int?
    public var competitorId: Int?
    public var name: String?
    /** Bare (scheme-less) domain */
    public var domain: String?

    public init(type: ModelType? = nil, id: Int? = nil, competitorId: Int? = nil, name: String? = nil, domain: String? = nil) {
        self.type = type
        self.id = id
        self.competitorId = competitorId
        self.name = name
        self.domain = domain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case competitorId = "competitor_id"
        case name
        case domain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(competitorId, forKey: .competitorId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(domain, forKey: .domain)
    }
}


extension Actor: Identifiable {}
