//
// AgentBotsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AgentBotsResponse: Sendable, Codable, Hashable {

    public var bots: [AgentBot]?
    public var companies: [String]?
    public var requestId: String?

    public init(bots: [AgentBot]? = nil, companies: [String]? = nil, requestId: String? = nil) {
        self.bots = bots
        self.companies = companies
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bots
        case companies
        case requestId = "request_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bots, forKey: .bots)
        try container.encodeIfPresent(companies, forKey: .companies)
        try container.encodeIfPresent(requestId, forKey: .requestId)
    }
}

