//
// AgentTrafficResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AgentTrafficResponse: Sendable, Codable, Hashable {

    public enum GroupBy: String, Sendable, Codable, CaseIterable {
        case bot = "bot"
        case company = "company"
    }
    public enum Granularity: String, Sendable, Codable, CaseIterable {
        case day = "day"
        case week = "week"
        case month = "month"
    }
    public var projectId: Int?
    public var from: Date?
    public var to: Date?
    public var groupBy: GroupBy?
    public var granularity: Granularity?
    public var totals: [String: Int]?
    public var timeseries: [String: [String: Int]]?
    public var requestId: String?

    public init(projectId: Int? = nil, from: Date? = nil, to: Date? = nil, groupBy: GroupBy? = nil, granularity: Granularity? = nil, totals: [String: Int]? = nil, timeseries: [String: [String: Int]]? = nil, requestId: String? = nil) {
        self.projectId = projectId
        self.from = from
        self.to = to
        self.groupBy = groupBy
        self.granularity = granularity
        self.totals = totals
        self.timeseries = timeseries
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case from
        case to
        case groupBy = "group_by"
        case granularity
        case totals
        case timeseries
        case requestId = "request_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(groupBy, forKey: .groupBy)
        try container.encodeIfPresent(granularity, forKey: .granularity)
        try container.encodeIfPresent(totals, forKey: .totals)
        try container.encodeIfPresent(timeseries, forKey: .timeseries)
        try container.encodeIfPresent(requestId, forKey: .requestId)
    }
}

