//
// ApiErrorError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiErrorError: Sendable, Codable, Hashable {

    public enum Code: String, Sendable, Codable, CaseIterable {
        case errMissingAuth = "ERR_MISSING_AUTH"
        case errInvalidApiKey = "ERR_INVALID_API_KEY"
        case errRevokedApiKey = "ERR_REVOKED_API_KEY"
        case errInsufficientScope = "ERR_INSUFFICIENT_SCOPE"
        case errInsufficientPermission = "ERR_INSUFFICIENT_PERMISSION"
        case errPlanRequired = "ERR_PLAN_REQUIRED"
        case errAccountInactive = "ERR_ACCOUNT_INACTIVE"
        case errDraftNotFound = "ERR_DRAFT_NOT_FOUND"
        case errDraftState = "ERR_DRAFT_STATE"
        case errProjectNotFound = "ERR_PROJECT_NOT_FOUND"
        case errNotFound = "ERR_NOT_FOUND"
        case errSearchConsoleNotConnected = "ERR_SEARCH_CONSOLE_NOT_CONNECTED"
        case errAiTrafficNotConnected = "ERR_AI_TRAFFIC_NOT_CONNECTED"
        case errAgentTrafficNotConnected = "ERR_AGENT_TRAFFIC_NOT_CONNECTED"
        case errInvalidParam = "ERR_INVALID_PARAM"
        case errInvalidRange = "ERR_INVALID_RANGE"
        case errLimitReached = "ERR_LIMIT_REACHED"
        case errQuotaExceeded = "ERR_QUOTA_EXCEEDED"
        case errRateLimited = "ERR_RATE_LIMITED"
    }
    public var code: Code?
    public var message: String?
    public var meta: JSONValue?

    public init(code: Code? = nil, message: String? = nil, meta: JSONValue? = nil) {
        self.code = code
        self.message = message
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}

