//
// AssignPromptTagsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssignPromptTagsRequest: Sendable, Codable, Hashable {

    public var projectId: Int
    public var promptIds: [Int]
    public var tagIds: [Int]?
    public var tagNames: [String]?
    public var createMissing: Bool?

    public init(projectId: Int, promptIds: [Int], tagIds: [Int]? = nil, tagNames: [String]? = nil, createMissing: Bool? = nil) {
        self.projectId = projectId
        self.promptIds = promptIds
        self.tagIds = tagIds
        self.tagNames = tagNames
        self.createMissing = createMissing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case promptIds = "prompt_ids"
        case tagIds = "tag_ids"
        case tagNames = "tag_names"
        case createMissing = "create_missing"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(promptIds, forKey: .promptIds)
        try container.encodeIfPresent(tagIds, forKey: .tagIds)
        try container.encodeIfPresent(tagNames, forKey: .tagNames)
        try container.encodeIfPresent(createMissing, forKey: .createMissing)
    }
}

