//
// Competitor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Competitor: Sendable, Codable, Hashable {

    public enum ActorType: String, Sendable, Codable, CaseIterable {
        case project = "project"
        case competitor = "competitor"
    }
    public var id: Int?
    public var name: String?
    public var domain: String?
    /** Only present when include_project_brand=true */
    public var actorType: ActorType?
    /** Only present when include_project_brand=true */
    public var isOwn: Bool?

    public init(id: Int? = nil, name: String? = nil, domain: String? = nil, actorType: ActorType? = nil, isOwn: Bool? = nil) {
        self.id = id
        self.name = name
        self.domain = domain
        self.actorType = actorType
        self.isOwn = isOwn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case domain
        case actorType = "actor_type"
        case isOwn = "is_own"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(actorType, forKey: .actorType)
        try container.encodeIfPresent(isOwn, forKey: .isOwn)
    }
}


extension Competitor: Identifiable {}
