//
// CompetitorDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CompetitorDetails: Sendable, Codable, Hashable {

    public var id: Int?
    public var projectId: Int?
    public var brandName: String?
    public var domain: String?
    public var matchingNames: [String]?
    public var googlePlayId: String?
    public var appStoreId: String?
    public var color: String?
    public var createdAt: Date?

    public init(id: Int? = nil, projectId: Int? = nil, brandName: String? = nil, domain: String? = nil, matchingNames: [String]? = nil, googlePlayId: String? = nil, appStoreId: String? = nil, color: String? = nil, createdAt: Date? = nil) {
        self.id = id
        self.projectId = projectId
        self.brandName = brandName
        self.domain = domain
        self.matchingNames = matchingNames
        self.googlePlayId = googlePlayId
        self.appStoreId = appStoreId
        self.color = color
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case projectId = "project_id"
        case brandName = "brand_name"
        case domain
        case matchingNames = "matching_names"
        case googlePlayId = "google_play_id"
        case appStoreId = "app_store_id"
        case color
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(brandName, forKey: .brandName)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(matchingNames, forKey: .matchingNames)
        try container.encodeIfPresent(googlePlayId, forKey: .googlePlayId)
        try container.encodeIfPresent(appStoreId, forKey: .appStoreId)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


extension CompetitorDetails: Identifiable {}
