//
// CreateAnnotationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateAnnotationRequest: Sendable, Codable, Hashable {

    public var projectId: Int
    public var title: String
    /** ISO YYYY-MM-DD; defaults to today */
    public var annotationDate: Date?
    public var description: String?
    /** Hex color, e.g. #2563eb */
    public var color: String?
    public var annotationCategoryId: Int?

    public init(projectId: Int, title: String, annotationDate: Date? = nil, description: String? = nil, color: String? = nil, annotationCategoryId: Int? = nil) {
        self.projectId = projectId
        self.title = title
        self.annotationDate = annotationDate
        self.description = description
        self.color = color
        self.annotationCategoryId = annotationCategoryId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case title
        case annotationDate = "annotation_date"
        case description
        case color
        case annotationCategoryId = "annotation_category_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(annotationDate, forKey: .annotationDate)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(annotationCategoryId, forKey: .annotationCategoryId)
    }
}

