//
// CreateWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateWebhookRequest: Sendable, Codable, Hashable {

    public enum EventType: String, Sendable, Codable, CaseIterable {
        case mentionPeriodCreated = "mention.created"
        case competitorMentionPeriodCreated = "competitor_mention.created"
        case citationPeriodCreated = "citation.created"
        case promptExecutionPeriodCompleted = "prompt_execution.completed"
        case sentimentPeriodNegativeDetected = "sentiment.negative_detected"
        case recommendationPeriodCompleted = "recommendation.completed"
        case intelligenceTaskPeriodCompleted = "intelligence_task.completed"
    }
    public var projectId: Int
    public var eventType: EventType
    /** Public HTTPS URL that will receive signed event payloads */
    public var targetUrl: String

    public init(projectId: Int, eventType: EventType, targetUrl: String) {
        self.projectId = projectId
        self.eventType = eventType
        self.targetUrl = targetUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case eventType = "event_type"
        case targetUrl = "target_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(targetUrl, forKey: .targetUrl)
    }
}

