//
// CreateTechnicalGeoReportsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateTechnicalGeoReportsRequest: Sendable, Codable, Hashable {

    public var projectId: Int
    public var url: String
    /** Defaults to the project country */
    public var countryCode: String?

    public init(projectId: Int, url: String, countryCode: String? = nil) {
        self.projectId = projectId
        self.url = url
        self.countryCode = countryCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case url
        case countryCode = "country_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
    }
}

