//
// DeleteWebhook200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeleteWebhook200Response: Sendable, Codable, Hashable {

    public var deleted: Bool?
    public var id: Int?
    public var requestId: String?

    public init(deleted: Bool? = nil, id: Int? = nil, requestId: String? = nil) {
        self.deleted = deleted
        self.id = id
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deleted
        case id
        case requestId = "request_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deleted, forKey: .deleted)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(requestId, forKey: .requestId)
    }
}


extension DeleteWebhook200Response: Identifiable {}
