//
// FinalizeProjectDraftRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FinalizeProjectDraftRequest: Sendable, Codable, Hashable {

    public var weeklyEmailSubscribed: Bool?
    public var executePromptsImmediately: Bool?

    public init(weeklyEmailSubscribed: Bool? = nil, executePromptsImmediately: Bool? = nil) {
        self.weeklyEmailSubscribed = weeklyEmailSubscribed
        self.executePromptsImmediately = executePromptsImmediately
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case weeklyEmailSubscribed = "weekly_email_subscribed"
        case executePromptsImmediately = "execute_prompts_immediately"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(weeklyEmailSubscribed, forKey: .weeklyEmailSubscribed)
        try container.encodeIfPresent(executePromptsImmediately, forKey: .executePromptsImmediately)
    }
}

