//
// GetAccount200ResponseSubscription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Billing state. Present only for callers who can access Billing and Plans in the app; absent otherwise. */
public struct GetAccount200ResponseSubscription: Sendable, Codable, Hashable {

    public var status: String?
    public var trialing: Bool?
    public var currentPeriodEndsAt: Date?

    public init(status: String? = nil, trialing: Bool? = nil, currentPeriodEndsAt: Date? = nil) {
        self.status = status
        self.trialing = trialing
        self.currentPeriodEndsAt = currentPeriodEndsAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case trialing
        case currentPeriodEndsAt = "current_period_ends_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(trialing, forKey: .trialing)
        try container.encodeIfPresent(currentPeriodEndsAt, forKey: .currentPeriodEndsAt)
    }
}

