//
// IntelligenceTaskUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IntelligenceTaskUpdateRequest: Sendable, Codable, Hashable {

    public var projectId: Int
    /** Dotted result_data paths (title, sections.0.content, key_points.2) mapped to their replacement text. Only string fields that already exist are editable; sections cannot be added or removed. */
    public var edits: [String: String]

    public init(projectId: Int, edits: [String: String]) {
        self.projectId = projectId
        self.edits = edits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case edits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(edits, forKey: .edits)
    }
}

