//
// LaunchRecommendationsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LaunchRecommendationsRequest: Sendable, Codable, Hashable {

    public enum RecommendationType: String, Sendable, Codable, CaseIterable {
        case aiVisibility = "ai_visibility"
        case socialCommunity = "social_community"
        case brandBuilding = "brand_building"
        case sentimentReputation = "sentiment_reputation"
    }
    public var projectId: Int
    public var recommendationType: RecommendationType? = .aiVisibility

    public init(projectId: Int, recommendationType: RecommendationType? = .aiVisibility) {
        self.projectId = projectId
        self.recommendationType = recommendationType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case recommendationType = "recommendation_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encodeIfPresent(recommendationType, forKey: .recommendationType)
    }
}

