//
// ListCompetitors200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListCompetitors200Response: Sendable, Codable, Hashable {

    public var projectId: Int?
    public var competitors: [Competitor]?

    public init(projectId: Int? = nil, competitors: [Competitor]? = nil) {
        self.projectId = projectId
        self.competitors = competitors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case competitors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(competitors, forKey: .competitors)
    }
}

