//
// LlmsTxtTechnicalGeoReportResultData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The files and generation details once the report has completed; null before that */
public struct LlmsTxtTechnicalGeoReportResultData: Sendable, Codable, Hashable {

    /** Current llms.txt, manual edits included */
    public var llmsTxtContent: String?
    /** Current llms-full.txt, manual edits included */
    public var llmsFullTxtContent: String?
    /** When the files were last edited by hand in the app, the API or MCP; null while they are as generated */
    public var manuallyEditedAt: Date?
    /** Send it back as content_version when editing the files. It changes on every save */
    public var contentVersion: String?
    /** The generated llms.txt, kept from the first manual edit; null while the files are as generated */
    public var originalLlmsTxtContent: String?
    /** The generated llms-full.txt, kept from the first manual edit; null while the files are as generated */
    public var originalLlmsFullTxtContent: String?
    public var crawlData: JSONValue?
    /** Generation details, including output_language_code, the language the files were written in */
    public var metadata: JSONValue?
    public var pagesCrawled: Int?
    public var generationTimeMs: Int?
    public var openaiTokensUsed: Int?

    public init(llmsTxtContent: String? = nil, llmsFullTxtContent: String? = nil, manuallyEditedAt: Date? = nil, contentVersion: String? = nil, originalLlmsTxtContent: String? = nil, originalLlmsFullTxtContent: String? = nil, crawlData: JSONValue? = nil, metadata: JSONValue? = nil, pagesCrawled: Int? = nil, generationTimeMs: Int? = nil, openaiTokensUsed: Int? = nil) {
        self.llmsTxtContent = llmsTxtContent
        self.llmsFullTxtContent = llmsFullTxtContent
        self.manuallyEditedAt = manuallyEditedAt
        self.contentVersion = contentVersion
        self.originalLlmsTxtContent = originalLlmsTxtContent
        self.originalLlmsFullTxtContent = originalLlmsFullTxtContent
        self.crawlData = crawlData
        self.metadata = metadata
        self.pagesCrawled = pagesCrawled
        self.generationTimeMs = generationTimeMs
        self.openaiTokensUsed = openaiTokensUsed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case llmsTxtContent = "llms_txt_content"
        case llmsFullTxtContent = "llms_full_txt_content"
        case manuallyEditedAt = "manually_edited_at"
        case contentVersion = "content_version"
        case originalLlmsTxtContent = "original_llms_txt_content"
        case originalLlmsFullTxtContent = "original_llms_full_txt_content"
        case crawlData = "crawl_data"
        case metadata
        case pagesCrawled = "pages_crawled"
        case generationTimeMs = "generation_time_ms"
        case openaiTokensUsed = "openai_tokens_used"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(llmsTxtContent, forKey: .llmsTxtContent)
        try container.encodeIfPresent(llmsFullTxtContent, forKey: .llmsFullTxtContent)
        try container.encodeIfPresent(manuallyEditedAt, forKey: .manuallyEditedAt)
        try container.encodeIfPresent(contentVersion, forKey: .contentVersion)
        try container.encodeIfPresent(originalLlmsTxtContent, forKey: .originalLlmsTxtContent)
        try container.encodeIfPresent(originalLlmsFullTxtContent, forKey: .originalLlmsFullTxtContent)
        try container.encodeIfPresent(crawlData, forKey: .crawlData)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(pagesCrawled, forKey: .pagesCrawled)
        try container.encodeIfPresent(generationTimeMs, forKey: .generationTimeMs)
        try container.encodeIfPresent(openaiTokensUsed, forKey: .openaiTokensUsed)
    }
}

