//
// LocalBusinessesTotals.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LocalBusinessesTotals: Sendable, Codable, Hashable {

    public var businesses: Int?
    public var yourBusinesses: Int?
    public var appearances: Int?
    public var avgRating: Double?
    public var executionsWithLocalBusinesses: Int?

    public init(businesses: Int? = nil, yourBusinesses: Int? = nil, appearances: Int? = nil, avgRating: Double? = nil, executionsWithLocalBusinesses: Int? = nil) {
        self.businesses = businesses
        self.yourBusinesses = yourBusinesses
        self.appearances = appearances
        self.avgRating = avgRating
        self.executionsWithLocalBusinesses = executionsWithLocalBusinesses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case businesses
        case yourBusinesses = "your_businesses"
        case appearances
        case avgRating = "avg_rating"
        case executionsWithLocalBusinesses = "executions_with_local_businesses"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(businesses, forKey: .businesses)
        try container.encodeIfPresent(yourBusinesses, forKey: .yourBusinesses)
        try container.encodeIfPresent(appearances, forKey: .appearances)
        try container.encodeIfPresent(avgRating, forKey: .avgRating)
        try container.encodeIfPresent(executionsWithLocalBusinesses, forKey: .executionsWithLocalBusinesses)
    }
}

