//
// LocalBusiness.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LocalBusiness: Sendable, Codable, Hashable {

    /** Stable grouping key: the lowercased name and address */
    public var businessKey: String?
    public var title: String?
    public var address: String?
    public var domain: String?
    public var url: String?
    public var phone: String?
    public var avgRating: Double?
    public var reviews: Int?
    /** Average rank of the business in the answer's list (1 = first) */
    public var avgPosition: Double?
    public var prompts: Int?
    public var appearances: Int?
    public var isClient: Bool?
    public var competitorId: Int?
    public var competitorName: String?

    public init(businessKey: String? = nil, title: String? = nil, address: String? = nil, domain: String? = nil, url: String? = nil, phone: String? = nil, avgRating: Double? = nil, reviews: Int? = nil, avgPosition: Double? = nil, prompts: Int? = nil, appearances: Int? = nil, isClient: Bool? = nil, competitorId: Int? = nil, competitorName: String? = nil) {
        self.businessKey = businessKey
        self.title = title
        self.address = address
        self.domain = domain
        self.url = url
        self.phone = phone
        self.avgRating = avgRating
        self.reviews = reviews
        self.avgPosition = avgPosition
        self.prompts = prompts
        self.appearances = appearances
        self.isClient = isClient
        self.competitorId = competitorId
        self.competitorName = competitorName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case businessKey = "business_key"
        case title
        case address
        case domain
        case url
        case phone
        case avgRating = "avg_rating"
        case reviews
        case avgPosition = "avg_position"
        case prompts
        case appearances
        case isClient = "is_client"
        case competitorId = "competitor_id"
        case competitorName = "competitor_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(businessKey, forKey: .businessKey)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(avgRating, forKey: .avgRating)
        try container.encodeIfPresent(reviews, forKey: .reviews)
        try container.encodeIfPresent(avgPosition, forKey: .avgPosition)
        try container.encodeIfPresent(prompts, forKey: .prompts)
        try container.encodeIfPresent(appearances, forKey: .appearances)
        try container.encodeIfPresent(isClient, forKey: .isClient)
        try container.encodeIfPresent(competitorId, forKey: .competitorId)
        try container.encodeIfPresent(competitorName, forKey: .competitorName)
    }
}

