//
// Ping200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Ping200Response: Sendable, Codable, Hashable {

    public var ok: Bool?
    public var userId: Int?
    public var project: Project?
    public var requestId: String?

    public init(ok: Bool? = nil, userId: Int? = nil, project: Project? = nil, requestId: String? = nil) {
        self.ok = ok
        self.userId = userId
        self.project = project
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case userId = "user_id"
        case project
        case requestId = "request_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ok, forKey: .ok)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(project, forKey: .project)
        try container.encodeIfPresent(requestId, forKey: .requestId)
    }
}

