//
// ProjectDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectDetails: Sendable, Codable, Hashable {

    public var id: Int?
    /** Internal project label (sidebar, settings, admin) */
    public var name: String?
    /** LLM-facing brand label (used in prompts and customer-facing charts). Defaults to `name` when not set. */
    public var brandName: String?
    public var url: String?
    public var description: String?
    public var matchingNames: [String]?
    public var industry: String?
    public var businessModel: String?
    /** Set only when business_model is OTHER */
    public var businessModelOther: String?
    public var primaryProducts: [String]?
    public var targetAudience: String?
    public var brandVoice: String?
    public var goals: String?
    public var countryCode: String?
    public var languageCode: String?
    public var paused: Bool?
    public var googlePlayId: String?
    public var appStoreId: String?
    public var createdAt: Date?
    public var stats: ProjectDetailsAllOfStats?

    public init(id: Int? = nil, name: String? = nil, brandName: String? = nil, url: String? = nil, description: String? = nil, matchingNames: [String]? = nil, industry: String? = nil, businessModel: String? = nil, businessModelOther: String? = nil, primaryProducts: [String]? = nil, targetAudience: String? = nil, brandVoice: String? = nil, goals: String? = nil, countryCode: String? = nil, languageCode: String? = nil, paused: Bool? = nil, googlePlayId: String? = nil, appStoreId: String? = nil, createdAt: Date? = nil, stats: ProjectDetailsAllOfStats? = nil) {
        self.id = id
        self.name = name
        self.brandName = brandName
        self.url = url
        self.description = description
        self.matchingNames = matchingNames
        self.industry = industry
        self.businessModel = businessModel
        self.businessModelOther = businessModelOther
        self.primaryProducts = primaryProducts
        self.targetAudience = targetAudience
        self.brandVoice = brandVoice
        self.goals = goals
        self.countryCode = countryCode
        self.languageCode = languageCode
        self.paused = paused
        self.googlePlayId = googlePlayId
        self.appStoreId = appStoreId
        self.createdAt = createdAt
        self.stats = stats
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case brandName = "brand_name"
        case url
        case description
        case matchingNames = "matching_names"
        case industry
        case businessModel = "business_model"
        case businessModelOther = "business_model_other"
        case primaryProducts = "primary_products"
        case targetAudience = "target_audience"
        case brandVoice = "brand_voice"
        case goals
        case countryCode = "country_code"
        case languageCode = "language_code"
        case paused
        case googlePlayId = "google_play_id"
        case appStoreId = "app_store_id"
        case createdAt = "created_at"
        case stats
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(brandName, forKey: .brandName)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(matchingNames, forKey: .matchingNames)
        try container.encodeIfPresent(industry, forKey: .industry)
        try container.encodeIfPresent(businessModel, forKey: .businessModel)
        try container.encodeIfPresent(businessModelOther, forKey: .businessModelOther)
        try container.encodeIfPresent(primaryProducts, forKey: .primaryProducts)
        try container.encodeIfPresent(targetAudience, forKey: .targetAudience)
        try container.encodeIfPresent(brandVoice, forKey: .brandVoice)
        try container.encodeIfPresent(goals, forKey: .goals)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
        try container.encodeIfPresent(languageCode, forKey: .languageCode)
        try container.encodeIfPresent(paused, forKey: .paused)
        try container.encodeIfPresent(googlePlayId, forKey: .googlePlayId)
        try container.encodeIfPresent(appStoreId, forKey: .appStoreId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(stats, forKey: .stats)
    }
}


extension ProjectDetails: Identifiable {}
