//
// ProjectCreateResponseCompetitors.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectCreateResponseCompetitors: Sendable, Codable, Hashable {

    public var created: Int?
    /** Always false; competitors are ready when the project transaction commits. */
    public var processing: Bool?

    public init(created: Int? = nil, processing: Bool? = nil) {
        self.created = created
        self.processing = processing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case created
        case processing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(processing, forKey: .processing)
    }
}

