//
// ProjectCreateRequestCompetitorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectCreateRequestCompetitorsInner: Sendable, Codable, Hashable {

    public var domain: String
    public var brandName: String?
    public var matchingNames: [String]?

    public init(domain: String, brandName: String? = nil, matchingNames: [String]? = nil) {
        self.domain = domain
        self.brandName = brandName
        self.matchingNames = matchingNames
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
        case brandName = "brand_name"
        case matchingNames = "matching_names"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(domain, forKey: .domain)
        try container.encodeIfPresent(brandName, forKey: .brandName)
        try container.encodeIfPresent(matchingNames, forKey: .matchingNames)
    }
}

