//
// ProjectCreateRequestOwnedMedia.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Requires Growth plan or above */
public struct ProjectCreateRequestOwnedMedia: Sendable, Codable, Hashable {

    public var youtubeChannelUrl: String?
    public var instagramProfileUrl: String?
    public var facebookPageUrl: String?
    public var tiktokProfileUrl: String?
    public var appStoreUrl: String?
    public var googlePlayUrl: String?

    public init(youtubeChannelUrl: String? = nil, instagramProfileUrl: String? = nil, facebookPageUrl: String? = nil, tiktokProfileUrl: String? = nil, appStoreUrl: String? = nil, googlePlayUrl: String? = nil) {
        self.youtubeChannelUrl = youtubeChannelUrl
        self.instagramProfileUrl = instagramProfileUrl
        self.facebookPageUrl = facebookPageUrl
        self.tiktokProfileUrl = tiktokProfileUrl
        self.appStoreUrl = appStoreUrl
        self.googlePlayUrl = googlePlayUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case youtubeChannelUrl = "youtube_channel_url"
        case instagramProfileUrl = "instagram_profile_url"
        case facebookPageUrl = "facebook_page_url"
        case tiktokProfileUrl = "tiktok_profile_url"
        case appStoreUrl = "app_store_url"
        case googlePlayUrl = "google_play_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(youtubeChannelUrl, forKey: .youtubeChannelUrl)
        try container.encodeIfPresent(instagramProfileUrl, forKey: .instagramProfileUrl)
        try container.encodeIfPresent(facebookPageUrl, forKey: .facebookPageUrl)
        try container.encodeIfPresent(tiktokProfileUrl, forKey: .tiktokProfileUrl)
        try container.encodeIfPresent(appStoreUrl, forKey: .appStoreUrl)
        try container.encodeIfPresent(googlePlayUrl, forKey: .googlePlayUrl)
    }
}

