//
// ProjectDetailsAllOfStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectDetailsAllOfStats: Sendable, Codable, Hashable {

    public var promptsCount: Int?
    public var competitorsCount: Int?
    public var collectionsCount: Int?

    public init(promptsCount: Int? = nil, competitorsCount: Int? = nil, collectionsCount: Int? = nil) {
        self.promptsCount = promptsCount
        self.competitorsCount = competitorsCount
        self.collectionsCount = collectionsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case promptsCount = "prompts_count"
        case competitorsCount = "competitors_count"
        case collectionsCount = "collections_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(promptsCount, forKey: .promptsCount)
        try container.encodeIfPresent(competitorsCount, forKey: .competitorsCount)
        try container.encodeIfPresent(collectionsCount, forKey: .collectionsCount)
    }
}

