//
// ProjectCreateResponsePrompts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectCreateResponsePrompts: Sendable, Codable, Hashable {

    public enum Execution: String, Sendable, Codable, CaseIterable {
        case immediate = "immediate"
        case deferredToNextScheduledRun = "deferred_to_next_scheduled_run"
    }
    public var created: Int?
    public var skipped: Int?
    public var execution: Execution?

    public init(created: Int? = nil, skipped: Int? = nil, execution: Execution? = nil) {
        self.created = created
        self.skipped = skipped
        self.execution = execution
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case created
        case skipped
        case execution
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(skipped, forKey: .skipped)
        try container.encodeIfPresent(execution, forKey: .execution)
    }
}

