//
// ProjectCreateResponseLimits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectCreateResponseLimits: Sendable, Codable, Hashable {

    public var projectsRemaining: Int?
    public var promptsAvailable: Int?
    public var competitorsRemaining: Int?

    public init(projectsRemaining: Int? = nil, promptsAvailable: Int? = nil, competitorsRemaining: Int? = nil) {
        self.projectsRemaining = projectsRemaining
        self.promptsAvailable = promptsAvailable
        self.competitorsRemaining = competitorsRemaining
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectsRemaining = "projects_remaining"
        case promptsAvailable = "prompts_available"
        case competitorsRemaining = "competitors_remaining"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectsRemaining, forKey: .projectsRemaining)
        try container.encodeIfPresent(promptsAvailable, forKey: .promptsAvailable)
        try container.encodeIfPresent(competitorsRemaining, forKey: .competitorsRemaining)
    }
}

