//
// ProjectCreateResponseCollectionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectCreateResponseCollectionsInner: Sendable, Codable, Hashable {

    public var id: Int?
    public var name: String?
    public var promptsAttached: Int?

    public init(id: Int? = nil, name: String? = nil, promptsAttached: Int? = nil) {
        self.id = id
        self.name = name
        self.promptsAttached = promptsAttached
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case promptsAttached = "prompts_attached"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(promptsAttached, forKey: .promptsAttached)
    }
}


extension ProjectCreateResponseCollectionsInner: Identifiable {}
