//
// ProjectCreateResponseEmailSubscription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectCreateResponseEmailSubscription: Sendable, Codable, Hashable {

    public var weeklyEmailSubscribed: Bool?

    public init(weeklyEmailSubscribed: Bool? = nil) {
        self.weeklyEmailSubscribed = weeklyEmailSubscribed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case weeklyEmailSubscribed = "weekly_email_subscribed"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(weeklyEmailSubscribed, forKey: .weeklyEmailSubscribed)
    }
}

