//
// PromptSummaryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PromptSummaryResponse: Sendable, Codable, Hashable {

    public var projectId: Int?
    public var from: Date?
    public var to: Date?
    public var filters: JSONValue?
    public var breakdown: String?
    public var sort: String?
    public var sortDir: String?
    public var page: Int?
    public var perPage: Int?
    public var total: Int?
    public var data: [PromptSummaryRow]?
    public var requestId: String?

    public init(projectId: Int? = nil, from: Date? = nil, to: Date? = nil, filters: JSONValue? = nil, breakdown: String? = nil, sort: String? = nil, sortDir: String? = nil, page: Int? = nil, perPage: Int? = nil, total: Int? = nil, data: [PromptSummaryRow]? = nil, requestId: String? = nil) {
        self.projectId = projectId
        self.from = from
        self.to = to
        self.filters = filters
        self.breakdown = breakdown
        self.sort = sort
        self.sortDir = sortDir
        self.page = page
        self.perPage = perPage
        self.total = total
        self.data = data
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case from
        case to
        case filters
        case breakdown
        case sort
        case sortDir = "sort_dir"
        case page
        case perPage = "per_page"
        case total
        case data
        case requestId = "request_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(filters, forKey: .filters)
        try container.encodeIfPresent(breakdown, forKey: .breakdown)
        try container.encodeIfPresent(sort, forKey: .sort)
        try container.encodeIfPresent(sortDir, forKey: .sortDir)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(perPage, forKey: .perPage)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(requestId, forKey: .requestId)
    }
}

