//
// PromptsCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PromptsCreateResponse: Sendable, Codable, Hashable {

    public var projectId: Int?
    public var created: Int?
    public var skipped: Int?
    public var totalAfter: Int?
    public var promptsAvailable: Int?
    public var data: [PromptsCreateResponseDataInner]?
    public var requestId: String?

    public init(projectId: Int? = nil, created: Int? = nil, skipped: Int? = nil, totalAfter: Int? = nil, promptsAvailable: Int? = nil, data: [PromptsCreateResponseDataInner]? = nil, requestId: String? = nil) {
        self.projectId = projectId
        self.created = created
        self.skipped = skipped
        self.totalAfter = totalAfter
        self.promptsAvailable = promptsAvailable
        self.data = data
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case created
        case skipped
        case totalAfter = "total_after"
        case promptsAvailable = "prompts_available"
        case data
        case requestId = "request_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(skipped, forKey: .skipped)
        try container.encodeIfPresent(totalAfter, forKey: .totalAfter)
        try container.encodeIfPresent(promptsAvailable, forKey: .promptsAvailable)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(requestId, forKey: .requestId)
    }
}

