//
// SampleWebhookPayloads200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SampleWebhookPayloads200ResponseDataInner: Sendable, Codable, Hashable {

    public var event: String?
    public var occurredAt: Date?
    public var projectId: Int?
    public var subscriptionId: Int?
    public var data: JSONValue?

    public init(event: String? = nil, occurredAt: Date? = nil, projectId: Int? = nil, subscriptionId: Int? = nil, data: JSONValue? = nil) {
        self.event = event
        self.occurredAt = occurredAt
        self.projectId = projectId
        self.subscriptionId = subscriptionId
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case event
        case occurredAt = "occurred_at"
        case projectId = "project_id"
        case subscriptionId = "subscription_id"
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encodeIfPresent(occurredAt, forKey: .occurredAt)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(subscriptionId, forKey: .subscriptionId)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

