//
// SearchConsoleFiltersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchConsoleFiltersInner: Sendable, Codable, Hashable {

    public enum Dimension: String, Sendable, Codable, CaseIterable {
        case country = "country"
        case device = "device"
        case page = "page"
        case query = "query"
        case searchappearance = "searchAppearance"
    }
    public enum Operator: String, Sendable, Codable, CaseIterable {
        case contains = "contains"
        case equals = "equals"
        case notcontains = "notContains"
        case notequals = "notEquals"
        case includingregex = "includingRegex"
        case excludingregex = "excludingRegex"
    }
    public static let expressionRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    public var dimension: Dimension
    public var _operator: Operator? = .contains
    public var expression: String

    public init(dimension: Dimension, _operator: Operator? = .contains, expression: String) {
        self.dimension = dimension
        self._operator = _operator
        self.expression = expression
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dimension
        case _operator = "operator"
        case expression
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dimension, forKey: .dimension)
        try container.encodeIfPresent(_operator, forKey: ._operator)
        try container.encode(expression, forKey: .expression)
    }
}

