//
// SovResponseSample.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The period the current shares were computed on (the last one with mentions), same shape as a periods item; null when the window has no mentions. */
public struct SovResponseSample: Sendable, Codable, Hashable {

    public var date: Date?
    public var mentions: Int?
    public var partial: Bool?
    public var confidence: String?
    public var marginOfError: Double?

    public init(date: Date? = nil, mentions: Int? = nil, partial: Bool? = nil, confidence: String? = nil, marginOfError: Double? = nil) {
        self.date = date
        self.mentions = mentions
        self.partial = partial
        self.confidence = confidence
        self.marginOfError = marginOfError
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case mentions
        case partial
        case confidence
        case marginOfError = "margin_of_error"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(mentions, forKey: .mentions)
        try container.encodeIfPresent(partial, forKey: .partial)
        try container.encodeIfPresent(confidence, forKey: .confidence)
        try container.encodeIfPresent(marginOfError, forKey: .marginOfError)
    }
}

