//
// SovResponsePeriodsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SovResponsePeriodsInner: Sendable, Codable, Hashable {

    public var date: Date?
    public var mentions: Int?
    public var partial: Bool?

    public init(date: Date? = nil, mentions: Int? = nil, partial: Bool? = nil) {
        self.date = date
        self.mentions = mentions
        self.partial = partial
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case mentions
        case partial
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(mentions, forKey: .mentions)
        try container.encodeIfPresent(partial, forKey: .partial)
    }
}

