//
// SummaryResponseAllOfPositionDistribution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SummaryResponseAllOfPositionDistribution: Sendable, Codable, Hashable {

    public var position1Count: Int?
    public var position2Count: Int?
    public var position3PlusCount: Int?
    public var totalMentions: Int?
    public var percentages: JSONValue?

    public init(position1Count: Int? = nil, position2Count: Int? = nil, position3PlusCount: Int? = nil, totalMentions: Int? = nil, percentages: JSONValue? = nil) {
        self.position1Count = position1Count
        self.position2Count = position2Count
        self.position3PlusCount = position3PlusCount
        self.totalMentions = totalMentions
        self.percentages = percentages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case position1Count = "position_1_count"
        case position2Count = "position_2_count"
        case position3PlusCount = "position_3_plus_count"
        case totalMentions = "total_mentions"
        case percentages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(position1Count, forKey: .position1Count)
        try container.encodeIfPresent(position2Count, forKey: .position2Count)
        try container.encodeIfPresent(position3PlusCount, forKey: .position3PlusCount)
        try container.encodeIfPresent(totalMentions, forKey: .totalMentions)
        try container.encodeIfPresent(percentages, forKey: .percentages)
    }
}

