//
// SummaryResponseAllOfSummaryValueInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SummaryResponseAllOfSummaryValueInner: Sendable, Codable, Hashable {

    public var actor: Actor?
    public var total: Double?
    public var min: Double?
    public var max: Double?
    public var last: Double?

    public init(actor: Actor? = nil, total: Double? = nil, min: Double? = nil, max: Double? = nil, last: Double? = nil) {
        self.actor = actor
        self.total = total
        self.min = min
        self.max = max
        self.last = last
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actor
        case total
        case min
        case max
        case last
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(actor, forKey: .actor)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(min, forKey: .min)
        try container.encodeIfPresent(max, forKey: .max)
        try container.encodeIfPresent(last, forKey: .last)
    }
}

