//
// SummaryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SummaryResponse: Sendable, Codable, Hashable {

    public var projectId: Int?
    public var from: Date?
    public var to: Date?
    public var granularity: String?
    public var filters: JSONValue?
    public var series: [String: [TimeseriesSeries]]?
    public var requestId: String?
    public var summary: [String: [SummaryResponseAllOfSummaryValueInner]]?
    public var positionDistribution: SummaryResponseAllOfPositionDistribution?

    public init(projectId: Int? = nil, from: Date? = nil, to: Date? = nil, granularity: String? = nil, filters: JSONValue? = nil, series: [String: [TimeseriesSeries]]? = nil, requestId: String? = nil, summary: [String: [SummaryResponseAllOfSummaryValueInner]]? = nil, positionDistribution: SummaryResponseAllOfPositionDistribution? = nil) {
        self.projectId = projectId
        self.from = from
        self.to = to
        self.granularity = granularity
        self.filters = filters
        self.series = series
        self.requestId = requestId
        self.summary = summary
        self.positionDistribution = positionDistribution
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case from
        case to
        case granularity
        case filters
        case series
        case requestId = "request_id"
        case summary
        case positionDistribution = "position_distribution"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(granularity, forKey: .granularity)
        try container.encodeIfPresent(filters, forKey: .filters)
        try container.encodeIfPresent(series, forKey: .series)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(summary, forKey: .summary)
        try container.encodeIfPresent(positionDistribution, forKey: .positionDistribution)
    }
}

