//
// TechnicalGeoReportContentUpdateRequestEdits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The files to replace, each mapped to its full replacement text: never blank, at most 200,000 characters. Send one file or both; a file identical to the stored one is ignored. */
public struct TechnicalGeoReportContentUpdateRequestEdits: Sendable, Codable, Hashable {

    /** Full text of llms.txt */
    public var llmsTxt: String?
    /** Full text of llms-full.txt */
    public var llmsFullTxt: String?

    public init(llmsTxt: String? = nil, llmsFullTxt: String? = nil) {
        self.llmsTxt = llmsTxt
        self.llmsFullTxt = llmsFullTxt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case llmsTxt = "llms_txt"
        case llmsFullTxt = "llms_full_txt"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(llmsTxt, forKey: .llmsTxt)
        try container.encodeIfPresent(llmsFullTxt, forKey: .llmsFullTxt)
    }
}

