//
// TechnicalGeoReportContentUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TechnicalGeoReportContentUpdateRequest: Sendable, Codable, Hashable {

    public enum ReportType: String, Sendable, Codable, CaseIterable {
        case llmsTxt = "llms_txt"
    }
    public var projectId: Int
    /** Only llms_txt reports have editable content */
    public var reportType: ReportType
    /** result_data.content_version of the report as last read. It changes on every save; a value that no longer matches is refused as stale */
    public var contentVersion: String
    public var edits: TechnicalGeoReportContentUpdateRequestEdits

    public init(projectId: Int, reportType: ReportType, contentVersion: String, edits: TechnicalGeoReportContentUpdateRequestEdits) {
        self.projectId = projectId
        self.reportType = reportType
        self.contentVersion = contentVersion
        self.edits = edits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case reportType = "report_type"
        case contentVersion = "content_version"
        case edits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(reportType, forKey: .reportType)
        try container.encode(contentVersion, forKey: .contentVersion)
        try container.encode(edits, forKey: .edits)
    }
}

