//
// TimeseriesPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimeseriesPoint: Sendable, Codable, Hashable {

    public var date: Date?
    public var value: Double?

    public init(date: Date? = nil, value: Double? = nil) {
        self.date = date
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

