//
// TimeseriesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimeseriesResponse: Sendable, Codable, Hashable {

    public var projectId: Int?
    public var from: Date?
    public var to: Date?
    public var granularity: String?
    public var filters: JSONValue?
    public var series: [String: [TimeseriesSeries]]?
    public var requestId: String?

    public init(projectId: Int? = nil, from: Date? = nil, to: Date? = nil, granularity: String? = nil, filters: JSONValue? = nil, series: [String: [TimeseriesSeries]]? = nil, requestId: String? = nil) {
        self.projectId = projectId
        self.from = from
        self.to = to
        self.granularity = granularity
        self.filters = filters
        self.series = series
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case from
        case to
        case granularity
        case filters
        case series
        case requestId = "request_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(granularity, forKey: .granularity)
        try container.encodeIfPresent(filters, forKey: .filters)
        try container.encodeIfPresent(series, forKey: .series)
        try container.encodeIfPresent(requestId, forKey: .requestId)
    }
}

