//
// TimeseriesSeries.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimeseriesSeries: Sendable, Codable, Hashable {

    public var actor: Actor?
    public var metric: String?
    public var data: [TimeseriesPoint]?

    public init(actor: Actor? = nil, metric: String? = nil, data: [TimeseriesPoint]? = nil) {
        self.actor = actor
        self.metric = metric
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actor
        case metric
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(actor, forKey: .actor)
        try container.encodeIfPresent(metric, forKey: .metric)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

