//
// TimeseriesPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimeseriesPoint: Sendable, Codable, Hashable {

    /** Calendar day in Europe/Madrid (YYYY-MM-DD). With granularity week or month it is the first day of the bucket (the Monday, or the 1st of the month). */
    public var date: Date?
    /** Null when the metric has no value for the bucket, e.g. a rate, position or sentiment metric on a day without answers. */
    public var value: Double?

    public init(date: Date? = nil, value: Double? = nil) {
        self.date = date
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

