//
// TopSourcesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TopSourcesResponse: Sendable, Codable, Hashable {

    public var projectId: Int?
    public var from: Date?
    public var to: Date?
    public var sort: String?
    public var page: Int?
    public var perPage: Int?
    public var total: Int?
    public var data: [TopSourcesResponseDataInner]?

    public init(projectId: Int? = nil, from: Date? = nil, to: Date? = nil, sort: String? = nil, page: Int? = nil, perPage: Int? = nil, total: Int? = nil, data: [TopSourcesResponseDataInner]? = nil) {
        self.projectId = projectId
        self.from = from
        self.to = to
        self.sort = sort
        self.page = page
        self.perPage = perPage
        self.total = total
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case from
        case to
        case sort
        case page
        case perPage = "per_page"
        case total
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(sort, forKey: .sort)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(perPage, forKey: .perPage)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

