//
// UpdateCompetitorRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateCompetitorRequest: Sendable, Codable, Hashable {

    public var projectId: Int
    public var brandName: String?
    public var matchingNames: [String]?
    /** Hex color, e.g. #1a2b3c */
    public var color: String?

    public init(projectId: Int, brandName: String? = nil, matchingNames: [String]? = nil, color: String? = nil) {
        self.projectId = projectId
        self.brandName = brandName
        self.matchingNames = matchingNames
        self.color = color
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case brandName = "brand_name"
        case matchingNames = "matching_names"
        case color
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encodeIfPresent(brandName, forKey: .brandName)
        try container.encodeIfPresent(matchingNames, forKey: .matchingNames)
        try container.encodeIfPresent(color, forKey: .color)
    }
}

